---
# tasks file for node_exporter
- name: Download and unpack node_exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Create systemd service file for node_exporter
  ansible.builtin.copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      [Service]
      ExecStart=/usr/local/bin/node_exporter
      [Install]
      WantedBy=multi-user.target

- name: Enable and start node_exporter service
  ansible.builtin.systemd:
    name: node_exporter
    daemon_reload: yes
    state: started
    enabled: yes
